sudo: false

language: ruby

rvm:
  - 2.5.0

cache: bundler
script: bundle exec middleman build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build
  on:
    branch: master